# docker-compose.yml
version: '3'

# services:
services:
  selenium:
    image:
    ports:
      - 8080:80
    restart: always
  app:
    build:
      context:
    volumes:
      - .app:/app
    command: sh -c "python3 main.py"
    depends_on:
      - selenium
